{% set name = "reform" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/gencorefacility/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 4e0e944250ec98d5165a844cdff1074194f0cf8061ef2e97ffb2446072a400d4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pgzip
    - biopython

test:
  imports:
    - reform

about:
  home: "https://github.com/gencorefacility/reform"
  license: "BSD-3-Clause"
  license_family: BSD
  license_file: LICENSE
  summary: "Tool for fast and robust editing of genome sequences and annotation files"
  doc_url: "https://gencore.bio.nyu.edu/reform"
  dev_url: "https://github.com/gencorefacility/reform"

extra:
  recipe-maintainers:
    - mohammedkhalfan
    - YuWei-CH
    - genericdata
  run_exports:
    - "{{ pin_subpackage('reform', max_pin='x.x') }}"